app_name = "metocs/oauth"

[server]
port = 8001
path = "/oauth"

[mysql]
ip = "192.168.31.95"
port = 3306
username = "metocs"
password = "s164857362"
database = "oauth"

[redis]
ip = "192.168.31.95"
port = 6379
password = "s164857362"
database = 15

[auth]
accessTokenExp = 2
refreshTokenExp = 3
isGenerateRefresh = true
clientId = "CDB3FA83A0BCFA83B0EE2FA4D786A72D"
clientSecret = "C4D17524AC59600DD43494B900D8A825"
grantType = "password"
