app_name = "metocs"

[server]
port = 8888
path = "/metocs"

[mysql]
ip = "192.168.31.95"
port = 3306
username = "metocs"
password = "s164857362"
database = "metocs"

[redis]
ip = "127.0.0.1"
port = 6379
password = "s164857362"

[auth]
secret = "my_secret_metocs"
expires = 2