app_name = "metocs/websocket"

[server]
port = 8002
path = "/websocket"

[mysql]
ip = "192.168.31.95"
port = 3306
username = "metocs"
password = "s164857362"
database = "websocket"

[redis]
ip = "192.168.31.95"
port = 6379
password = "s164857362"